# Generated by Django 3.2.13 on 2022-07-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
    ]
